### ISSUE TITLE
Integrate lazy connected components code with appropriate ilastik applets

### ISSUE THREAD

**Issue by stuarteberg** [ilastik/ilastik#1020]
@burgerdev's new lazy connected components work was merged into lazyflow, but it is not yet being used by ilastik.  We need to integrate it into the thresholding applet (any others?)

(Assigned to @akreshuk for now until she decides who to re-assign it to...)

Edit by @burgerdev (below):

Remaining ToDos:
- [ ] integrate lazy `OpFilterLabels` into lazyflow (ilastik/lazyflow#158)
- [ ] use lazy operators depending on config setting in `OpThresholdTwoLevels` (should enable lazy object classification automagically)
- [ ] use lazy operators where needed (tracking??)

**Comment by burgerdev** [comment]
Remaining ToDos:

  * [ ] integrate lazy `OpFilterLabels` into lazyflow (ilastik/lazyflow#158)
  * [ ] use lazy operators depending on config setting in `OpThresholdTwoLevels` (should enable lazy object classification automagically)
  * [ ] use lazy operators where needed (tracking??)

**Comment by burgerdev** [comment]
Waiting for #1135 and ilastik/lazyflow#158, after they are merged we can tick the first two boxes.
